sudo: required

language: generic

env:
  OS: linux

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
        key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common 
      - docker-ce
      - openjdk-8-jdk

install:
  - docker version

before_script:
  - ls -lah

script:
  - echo "$HUB_PASSWORD" | docker login --username $HUB_USERNAME --password-stdin
  - docker build -t michaeltigr/zebra-jmeter-taurus:${TRAVIS_BRANCH}-travis . && docker push michaeltigr/zebra-jmeter-taurus:${TRAVIS_BRANCH}-travis
